### ISSUE TITLE
"Missing Comment"

### ISSUE THREAD

**Issue by digitalbuddha** [ggrell/RxReactor#1]
https://github.com/ggrell/RxReactor/blob/f169aeccfec9f51bbd86a382c63eab9c1e22e635/sample/src/main/java/com/gyurigrell/rxreactor2/sample/ContactService.kt#L6

**Comment by ggrell** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/2f647201-bd6b-465b-a502-89fe712142db-2916fb3c-c35f-4d74-a226-8b29dbaeb3e6-v1.png?transparent=1&palette=1&width=246)

Yup, that's part of my file header template in Android Studio, IntelliJ & AppCode. Definitely, need to clean some things up!

**Comment by ggrell** [comment]
!(ship it)[https://media.giphy.com/media/HpiwI8SrIg7XW/giphy.gif]

**Comment by ggrell** [comment]
LOL removed gif comment, just noticed dude was giving the finger which, didn't want to imply anything 😄
